---
# zshはhomebrewでインストール

- name: zsh | clone zinit
  become_user: "{{ ansible_exec_user }}"
  git:
    repo: "https://github.com/zdharma-continuum/zinit"
    dest: "{{ xdg_data_home }}/zinit/bin"
    clone: true

- name: zsh | Create link for .zshenv
  become_user: "{{ ansible_exec_user }}"
  file:
    state: link
    src: "{{ xdg_config_home }}/zsh/.zshenv"
    dest: "{{ ansible_exec_user_home }}/.zshenv"

- name: zsh | Create link for .zprofile
  become_user: "{{ ansible_exec_user }}"
  file:
    state: link
    src: "{{ xdg_config_home }}/zsh/.zprofile"
    dest: "{{ ansible_exec_user_home }}/.zprofile"

- name: zsh | Change user shell to zsh
  user:
    name: "{{ ansible_exec_user }}"
    shell: /home/linuxbrew/.linuxbrew/bin/zsh

- name: zsh | create xdg directory
  become_user: "{{ ansible_exec_user }}"
  file:
    state: directory
    path: "{{ item }}"
    mode: "0755"
  with_items:
    - "{{ xdg_data_home }}"
    - "{{ xdg_state_home }}"
