---
- name: ssh | Disable SendEnv option
  lineinfile:
    path: /etc/ssh/ssh_config
    state: "present"
    regexp: ^(\s*)SendEnv(.*)$
    backrefs: yes
    line: '#\1SendEnv\2'

- name: ssh | Start SSH server
  service:
    name: ssh
    state: started

- name: ssh | Enable ssh.service
  service:
    name: ssh
    enabled: yes
