---
# site.ymlからリポジトリルートまでの相対パス
path_to_root: ".."
repo_root_path: "{{ playbook_dir }}/{{ path_to_root }}"
config_directory_path: "{{ repo_root_path }}/config"

# --extra-varsオプションを使い、実行時に変数を定義する
ansible_exec_user: ""
ansible_exec_user_home: ""

# XDG Base Directory Specification
xdg_config_home: "{{ ansible_exec_user_home }}/.config"
xdg_data_home: "{{ ansible_exec_user_home }}/.local/share"
xdg_state_home: "{{ ansible_exec_user_home }}/.local/state"
