[tools]
node = "24"
python = "latest"
deno = "latest"
rust = "latest"
bun = "latest"
pnpm = "latest"
go = "latest"
java = "21"
"npm:@google/gemini-cli" = "latest"
"npm:@openai/codex" = "latest"
"npm:@anthropic-ai/sandbox-runtime" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python"]
